## Basic Configuration

baseurl = "https://otman.ca"
builddrafts = true
canonifyurls = true
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Otman Benchekroun"
title = "Otman Benchekroun"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "" #""https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = false

## Site Settings
[params]
author = "Otman Benchekroun"
intro = "Graduate Student in Computer Graphics"
description = ""
authorimage = "profile2.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Otman Benchekroun"
keywords = "research, computer graphics, animation, geometry"

## Social Accounts
[params.social]
github = "otmanon"
#instagram = "<username>"
#xing = "<username>"
#linkedin = "<username>"
twitter = "egotman"
#facebook = "<username>"
#google = "<username>"
#googlescholar = "<account_id>"
#stackoverflow = "<username>"
#lastfm = "<username>"
#goodreads = "<username>"
#gitlab = "<username>"
#bitbucket = "<username>"
#fivehundredpx = "<username>"
#flickr = "<username>"
#foursquare = "<username>"
#hackernews = "<username>"
#kickstarter = "<username>"
#patreon = "<username>"
#pintrest = "<username>"
#steam = "<username>"
#reddit = "<username>"
#snapchat = "<username>"
#youtube = "<channelid>"
#keybase = "<username>"
#twitch = "<username>"
#soundcloud = "<username>"
#tumblr = "<username>"
#strava = "<username>"
#skype = "<username>"
#telegram = "<username>"
#whatsapp = "<username>"
#buymeacoffee = "<username>"
#kaggle = "<username>"
email = "otman.benchekroun@mail.utoronto.ca"
#pgp = "<key_fingerprint>"

## Extras
[params.extra]
copyright = ""
poweredby = false
highlightjs = false
socialmarkup = false
toc = false
displayrssicon = false


## Main Menu
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "publications"
    identifier = "publications"
    weight = 300
    url = "/publications/"
[[menu.main]]
    name = "posts"
    weight = 5000
    identifier = "posts"
    url = "/posts/"
